[package]
name = "kfs"
version = "0.1.0"
edition = "2021"

[lib]
crate-type = ["staticlib"]

[dependencies]
bit_field = "0.10.2"
pc-keyboard = "0.5.0"
pic8259 = "0.10.1"
rlibc = "1.0"
spin = "0.5.2"
volatile = "0.2.6"
x86_64 = "0.14.2"

[dependencies.lazy_static]
version = "1.0"
features = ["spin_no_std"]
